### PR TITLE
Changes for release 16.0.0

### PR DESCRIPTION
**Pull request by nwbirnie**
Here's the result of running the release script in PR form :)

### CODE REVIEW

**Review by jradcliff — COMMENTED** [review]
Does this require a merge commit? We have merge commits disabled on our repo.

**Comment by nwbirnie** [comment]
Yes, a merge or a rebase and merge, I mean the alternative is we send two PRs... why are merge commits disabled?

**Comment by nwbirnie** [comment]
Also, more to the point, how do we disable that to merge these changes?

**Comment by nwbirnie** [comment]
Found it :)

**Review by jradcliff — APPROVED** [review]
I'm OK with you enabling merge commits for the moment. I'll ping you separately to provide the background on why we disabled them.

**Review by devchas — APPROVED** [review]

**Pull request merged**
